// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADotQhP0j7_s81z_NeEHKk0FcumJ_Oa44',
    appId: '1:503746643543:web:84e16460f39225a9100512',
    messagingSenderId: '503746643543',
    projectId: 'fir-demo-d1167',
    authDomain: 'fir-demo-d1167.firebaseapp.com',
    databaseURL: 'https://fir-demo-d1167-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-d1167.appspot.com',
    measurementId: 'G-KP309V7DDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8w9SiiaM47BnH5JYcARp1jiSB2RmHFlo',
    appId: '1:503746643543:android:e928459aaa9022f7100512',
    messagingSenderId: '503746643543',
    projectId: 'fir-demo-d1167',
    databaseURL: 'https://fir-demo-d1167-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-d1167.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1XbjOh4cGs7dT4HIXm53hrIAAGDpQ0A',
    appId: '1:503746643543:ios:25c94e80ffbf0b7a100512',
    messagingSenderId: '503746643543',
    projectId: 'fir-demo-d1167',
    databaseURL: 'https://fir-demo-d1167-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-d1167.appspot.com',
    iosBundleId: 'com.example.campusGigs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1XbjOh4cGs7dT4HIXm53hrIAAGDpQ0A',
    appId: '1:503746643543:ios:25c94e80ffbf0b7a100512',
    messagingSenderId: '503746643543',
    projectId: 'fir-demo-d1167',
    databaseURL: 'https://fir-demo-d1167-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-d1167.appspot.com',
    iosBundleId: 'com.example.campusGigs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADotQhP0j7_s81z_NeEHKk0FcumJ_Oa44',
    appId: '1:503746643543:web:3d348311bed1d499100512',
    messagingSenderId: '503746643543',
    projectId: 'fir-demo-d1167',
    authDomain: 'fir-demo-d1167.firebaseapp.com',
    databaseURL: 'https://fir-demo-d1167-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-d1167.appspot.com',
    measurementId: 'G-6YLW7NRHXT',
  );
}
